### ISSUE TITLE
Card tooltips on mobile

### ISSUE THREAD

**Issue by Donrafaeli** [SebastianZaha/wordpress_mtg_tooltips#2]
Currently on mobile, when pressing a card name, a link to deckbox instantly opens, along with the image of the card.

I was thinking, is there a simple way of implementing smarter card tooltip images on mobile?

For example, pressing once opens the image, and pressing another time opens the link on deckbox?

I'm not very familiar with PHP, but maybe someone more knowledgeable might chip in :)

**Comment by SebastianZaha** [comment]
A extremely late reply here, but better late than never :). This is working as of an update a year ago or so.
