### ISSUE TITLE
Links to Deckbox are broken if a word in card name ends with an aphostrophe

### ISSUE THREAD

**Issue by PhilippKilian** [SebastianZaha/wordpress_mtg_tooltips#4]
The preview picture and the link are broken if a word in the card name ends with an non texturized aphostrophe.

Example:
The card `Shapers' Sanctuary` get's an texturized aphostrophe and it's impossible to get a preview of this card.

**Comment by SebastianZaha** [comment]
Hello,

I just tried and it seems it works for me, do you have a page where this does not work, so I can inspect the generated html for the link? What wordpress version are you using?

**Comment by PhilippKilian** [comment]
> Hello,
> 
> I just tried and it seems it works for me, do you have a page where this does not work, so I can inspect the generated html for the link? What wordpress version are you using?

Hi @SebastianZaha You can see it on this page (first deck in list, Sideboard): https://linvala.de/2022/07/31/big-pioneer-top-4/

The Wordpress Version is 6.0.1.

**Comment by SebastianZaha** [comment]
Thanks!

Fixed now from serverside to convert weird quotes to simple quotes. If you don't see the new image directly, Shift-Refresh the page to clean cache should do the trick.

I bumped the plugin version to 3.3.0 for the other issue of the width.
