### ISSUE TITLE
Max-width of 510px is to small for embedded deck

### ISSUE THREAD

**Issue by PhilippKilian** [SebastianZaha/wordpress_mtg_tooltips#5]
The max-width in the mtg_deck table is to small if used with embedded pictures on a non-mobil device. On mobil it looks fine, but on Desktop it's heavily clinched.

Codeline: https://github.com/SebastianZaha/wordpress_mtg_tooltips/blob/473ef46c968ebd9e29547f4b0b706168f920c0c8/wp_deckbox_mtg.php#L271)

Maybe using 100% or 1000px is a better solution that it looks good on mobil and non-mobil devices.

**Comment by SebastianZaha** [comment]
This was set to such a small value since I think wordpress default theme has the posts max-width: 650px;, so this seemed appropriate. What theme are you using, could you link a page so that I can try out some css values? In any case I would try to add this as an option i think so as not to break existing users of the plugin, since it has been like this since the beginning.

**Comment by PhilippKilian** [comment]
> This was set to such a small value since I think wordpress default theme has the posts max-width: 650px;, so this seemed appropriate. What theme are you using, could you link a page so that I can try out some css values? In any case I would try to add this as an option i think so as not to break existing users of the plugin, since it has been like this since the beginning.

@SebastianZaha I'm using "Spice Software Theme", without widgets on the right side (Widgets are in footer). A page you can see where I'm using it is: https://linvala.de/2022/07/17/storechampionship-modern-top-8/

As a note: I have edited the value in the php code line to 1000 on the webserver, so it' looks how it looks now.

**Comment by SebastianZaha** [comment]
Fixed to add 100% width.

The max-width setting is actually modifiable from wordpress setting page for the plugin. (wp_admin -> Settings -> Deckbox Tooltips).
